import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/farari.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Button , Card, CardGroup} from 'react-bootstrap';
import Col from 'react-bootstrap/Col';
import Row from 'react-bootstrap/Row';
import Carousel from 'react-bootstrap/Carousel';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          About  <a href="https://nextjs.org">Ferrari!</a>
        </h1>

        <p className={styles.description}>
         </p>
        
        <div>
        <Image src="/1.jpg" alt="pic2" width="400%" height="300px;"/>
           <span> <h2>Ferrari</h2>
            <p>Automatic</p>
            <h4>45.00 lakh onwards</h4>
            </span>
        </div>

        <Carousel className={styles.aa}>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="/a.jpg"
          alt="First slide"
        />
        <Carousel.Caption>
          <h3>First slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="/b.jpg"
          alt="Second slide"
        />

        <Carousel.Caption>
          <h3>Second slide label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="/c.jpg"
          alt="Third slide"
        />

        <Carousel.Caption>
          <h3>Third slide label</h3>
          <p>
            Praesent commodo cursus magna, vel scelerisque nisl consectetur.
          </p>
        </Carousel.Caption>
      </Carousel.Item>
    </Carousel>
    {/* <Carousel className={styles.aa}> */}
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="/d.jpg"
          alt="Fourth slide"
        />
        <Carousel.Caption>
          <h3>First slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item></Carousel.Item><br></br>
       


      </main>
      <h5 className={styles.grid}>Latest Cars in India</h5><br></br>
      <CardGroup>
      <Card>
        <Card.Img variant="top" src="/14.jpg" />
        <Card.Body>
          <Card.Title>Ferrari</Card.Title>
          <Card.Text>
          <p>Automatic</p>
          <div className={styles.ab}>
              <a href="\cars\ferrari1">view details</a>
            </div>
            
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
      <Card>
        <Card.Img variant="top" src="/11.jpg" />
        <Card.Body>
          <Card.Title>Ferrari</Card.Title>
          <Card.Text>
          <p>Automatic</p>
          <div className={styles.ab}>
              <a href="\cars\farari">view details</a>
            </div>
            
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
      <Card>
        <Card.Img variant="top" src="/13.jpg" />
        <Card.Body>
          <Card.Title>Ferrari</Card.Title>
          <Card.Text>
          <p>Automatic</p>
          <div className={styles.ab}>
              <a href="\cars\farari">view details</a>
            </div>
            
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
    </CardGroup><br></br>
    
   

  <h5 className={styles.grid}>Latest Bike</h5><br></br>
    <Row xs={1} md={2} className="g-4">
      {Array.from({ length: 4 }).map((_, idx) => (
        <Col>
          <Card>
            <Card.Img variant="top" src="/6.jpg" />
            <Card.Body>
              <Card.Title>Apachee</Card.Title>
              <Card.Text>
                This is a longer card with supporting text below as a natural
                lead-in to additional content. This content is a little bit
                longer.
              </Card.Text>
            </Card.Body>
          </Card>
        </Col>
      ))}
    </Row>
  

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
