import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Carousel from 'react-bootstrap/Carousel';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Button , Card, CardGroup} from 'react-bootstrap';
import Col from 'react-bootstrap/Col';
import Row from 'react-bootstrap/Row';
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavDropdown from 'react-bootstrap/NavDropdown';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <Navbar bg="light" expand="lg">
      <Container>
        <Navbar.Brand href="#home">React-Bootstrap</Navbar.Brand>
        <Navbar.Toggle aria-controls="basic-navbar-nav" />
        <Navbar.Collapse id="basic-navbar-nav">
          <Nav className="me-auto">
            <Nav.Link href="#home">Home</Nav.Link>
            <Nav.Link href="#link">Link</Nav.Link>
            <NavDropdown title="Dropdown" id="basic-nav-dropdown">
              <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
              <NavDropdown.Item href="#action/3.2">
                Another action
              </NavDropdown.Item>
              <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
              <NavDropdown.Divider />
              <NavDropdown.Item href="#action/3.4">
                Separated link
              </NavDropdown.Item>
            </NavDropdown>
          </Nav>
        </Navbar.Collapse>
      </Container>
    </Navbar>


      {/* <Carousel className={styles.aa}>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="/3.jpg"
          alt="First slide"
        />
        <Carousel.Caption>
          <h3>First slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="/1.jpg"
          alt="Second slide"
        />

        <Carousel.Caption>
          <h3>Second slide label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="/2.jpg"
          alt="Third slide"
        />

        <Carousel.Caption>
          <h3>Third slide label</h3>
          <p>
            Praesent commodo cursus magna, vel scelerisque nisl consectetur.
          </p>
        </Carousel.Caption>
      </Carousel.Item>
    </Carousel><br></br>
        */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.carbike360.com/">Car Bike company</a>
        </h1><br></br>

        <div className={styles.grid}>

          <div className={styles.card}>
            <Image src="/1.jpg" alt="pic1" width="400px" height="300px;"/>
            <h4><h2>ferrari</h2>
            <h6>Automatic</h6>
            <h4>45.00 lakh onwards</h4>
            <div className={styles.ab}>
              <a href="\cars\farari">view details</a>
            </div></h4>
          </div>
          <div className={styles.card}>
            <Image src="/5.jpg" alt="pic2" width="400%" height="300px;"/>
           <h4> <h2>scorpio</h2>
            <h6>Manual</h6>
            <h4>15.00 lakh onwards</h4>
            <div className={styles.ab}>
              <a href="/cars/scorpio">view details</a>
            </div></h4>
          </div>
          <div className={styles.grid}>
          <div className={styles.card}>
            <Image src="/3.jpg" alt="pic3" width="400%" height="300px;"/>
           <div className={styles.abcd}>
           <h4> <h2>TATA</h2>
            <h4><h6>Automatic</h6></h4>
            <h4>10.00 lakh onwards</h4>
            <div className={styles.ab}>
              <a href="/cars/TATA">view details</a>
              </div></h4>
            </div>
          </div>

          <div className={styles.card}>
            <Image src="/4.jpg" alt="pic4" width="400%" height="300px;"/>
           <h4> <h2>Glanza</h2>
            <h6>Manual</h6>
            <h4>15.00 lakh onwards</h4>
            <div className={styles.ab}>
              <a href="/cars/Glanza">view details</a>
            </div></h4>
          </div>
          </div>

          <div className={styles.card}>
            <Image src="/6.jpg" alt="pic2" width="400%" height="300px;"/>
            <h4><h2>Apachee</h2>
            <h6>Automatic</h6>
            <h4>3 lakh onwards</h4>
            <div className={styles.ab}>
              <a href="/cars/Apachee">view details</a>
            </div></h4>
          </div>

          <div className={styles.card}>
            <Image src="/7.jpg" alt="pic2" width="400%" height="300px;"/>
            <h4><h2>KTM</h2>
            <h6>Manual</h6>
            <h4>1.98 lakh onwards</h4>
            <div className={styles.ab}>
              <a href="\cars\KTM">view details</a>
            </div></h4>
          </div>
          
          <div className={styles.card}>
            <Image src="/9.jpg" alt="pic2" width="400%" height="300px;"/>
            <h4><h2>Splendor</h2>
            <h6>Automatic</h6>
            <h4>Rs.81000 onwards</h4>
            <div className={styles.ab}>
              <a href="\cars\Splendor">view details</a>
            </div></h4>
          </div>
          
         
          <div className={styles.card}>
            <Image src="/10.jpg" alt="pic2" width="400%" height="300px;"/>
            <h4><h2>Bajaj Pulsar</h2>
            <h6>Automatic</h6>
            <h4>Rs.99000 onwards</h4>
            <div className={styles.ab}>
              <a href="\cars\Bajaj Pulsar">view details</a>
            </div></h4>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

